[package]
name = "rustical_auth"
version = "0.1.0"
edition = "2021"

[dependencies]
actix-web = "4.9"
actix-web-httpauth = "0.8"
futures-util = "0.3"
password-auth = "1.0"
serde = { version = "1.0", features = ["derive"] }
thiserror = "1.0"
