[package]
name = "rustical"
version = "0.1.0"
edition = "2021"

[dependencies]
rustical_store = { path = "./crates/store/" }
rustical_auth = { path = "./crates/auth/" }
rustical_api = { path = "./crates/api/" }
rustical_caldav = { path = "./crates/caldav/" }
serde = { version = "1.0", features = ["derive"] }
tokio = { version = "1.35", features = [
  "net",
  "tracing",
  "macros",
  "rt-multi-thread",
  "full",
] }
tracing = "0.1"
env_logger = "0.11"
actix-web = "4.4"
anyhow = { version = "1.0", features = ["backtrace"] }
toml = "0.8"
clap = { version = "4.4", features = ["derive", "env"] }
sqlx = { version = "0.7", features = [
  "sqlx-sqlite",
  "sqlx-postgres",
  "uuid",
  "time",
  "chrono",
  "postgres",
  "sqlite",
  "runtime-tokio",
  "migrate",
] }
async-trait = "0.1"
