[package]
name = "rustical"
version = "0.1.0"
edition = "2021"
resolver = "2"

[workspace]
members = ["crates/*"]

[dependencies]
rustical_store = { path = "./crates/store/" }
rustical_auth = { path = "./crates/auth/" }
rustical_caldav = { path = "./crates/caldav/" }
rustical_carddav = { path = "./crates/carddav/" }
rustical_frontend = { path = "./crates/frontend/" }
serde = { version = "1.0", features = ["derive"] }
tokio = { version = "1.39", features = [
  "net",
  "tracing",
  "macros",
  "rt-multi-thread",
  "full",
] }
tracing = "0.1"
env_logger = "0.11"
actix-web = "4.8"
anyhow = { version = "1.0", features = ["backtrace"] }
toml = "0.8"
clap = { version = "4.5", features = ["derive", "env"] }
sqlx = { version = "0.8", features = [
  "sqlx-sqlite",
  "sqlx-postgres",
  "uuid",
  "chrono",
  "postgres",
  "sqlite",
  "runtime-tokio",
  "migrate",
] }
async-trait = "0.1"
