[package]
name = "rustical"
version = "0.1.0"
edition = "2021"

[dependencies]
rustical_store = { path = "./crates/store/" }
rustical_api = { path = "./crates/api/" }
rustical_dav = { path = "./crates/dav/" }
serde = { version = "1.0.188", features = ["derive"] }
tokio = { version = "1.32.0", features = [
  "net",
  "tracing",
  "macros",
  "rt-multi-thread",
  "full",
] }
tracing = "0.1.37"
env_logger = "0.10.0"
actix-web = "4.4.0"
anyhow = { version = "1.0.75", features = ["backtrace"] }
serde_json = "1.0.105"
toml = "0.7.6"
clap = { version = "4.4.2", features = ["derive", "env"] }
