[package]
name = "rustical_caldav"
version = "0.1.0"
edition = "2021"

[dependencies]
actix-web = "4.9"
actix-web-httpauth = "0.8"
anyhow = { version = "1.0", features = ["backtrace"] }
base64 = "0.22"
futures-util = "0.3"
quick-xml = { version = "0.36", features = [
  "serde",
  "serde-types",
  "serialize",
] }
roxmltree = "0.20"
rustical_store = { path = "../store/" }
rustical_dav = { path = "../dav/" }
serde = { version = "1.0", features = ["serde_derive", "derive"] }
serde_json = "1.0"
tokio = { version = "1.40", features = ["sync", "full"] }
async-trait = "0.1"
thiserror = "1.0"
strum = { version = "0.26", features = ["strum_macros", "derive"] }
derive_more = { version = "1.0", features = ["from", "into"] }
url = "2.5.2"
