[package]
name = "rustical_api"
version = "0.1.0"
edition = "2021"

[dependencies]
actix-web = "4.4"
anyhow = { version = "1.0", features = ["backtrace"] }
rustical_store = { path = "../store/" }
serde = "1.0"
serde_json = "1.0"
tokio = { version = "1.32", features = ["sync"] }
