[package]
name = "rustical_store"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
anyhow = { version = "1.0", features = ["backtrace"] }
async-trait = "0.1"
serde = { version = "1.0", features = ["derive", "rc"] }
sha2 = "0.10"
sqlx = { version = "0.7", features = [
  "sqlx-sqlite",
  "sqlx-postgres",
  "uuid",
  "time",
  "chrono",
  "postgres",
  "sqlite",
  "runtime-tokio",
  "migrate",
] }
tokio = { version = "1.35", features = ["sync", "full"] }
toml = "0.8"
ical = { version = "0.10", features = ["generator", "serde"] }
chrono = "0.4"
regex = "1.10"
lazy_static = "1.4"
rstest = "0.18.2"
rstest_reuse = "0.6.0"
thiserror = "1.0.61"
