[package]
name = "rustical_store"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
anyhow = { version = "1.0.75", features = ["backtrace"] }
async-trait = "0.1.73"
serde = { version = "1.0.188", features = ["derive", "rc"] }
sha2 = "0.10.7"
sqlx = { version = "0.7.1", features = [
  "sqlx-sqlite",
  "sqlx-postgres",
  "uuid",
  "time",
  "chrono",
  "postgres",
  "sqlite",
  "runtime-tokio",
] }
tokio = { version = "1.32.0", features = ["sync", "full"] }
toml = "0.7.6"
