[package]
name = "rustical_dav"
version = "0.1.0"
edition = "2021"

[dependencies]
actix-web = "4.4"
anyhow = "1.0"
async-trait = "0.1"
derive_more = "0.99"
futures-util = "0.3"
quick-xml = "0.31"
rustical_auth = { path = "../auth/" }
serde = { version = "1.0.197", features = ["derive"] }
strum = "0.26"
itertools = "0.12"
thiserror = "1.0"
