[package]
name = "rustical_dav"
version = "0.1.0"
edition = "2021"

[dependencies]
actix-web = "4.4.0"
anyhow = "1.0.75"
async-trait = "0.1.73"
derive_more = "0.99.17"
futures-util = "0.3.28"
quick-xml = "0.30.0"
rustical_auth = { path = "../auth/" }
