name: "CICD"
on: [push, pull_request]
permissions:
  contents: read
  pull-requests: write

env:
  CARGO_TERM_COLOR: always

jobs:
  check:
    name: Check
    runs-on: ubuntu-latest
    steps:
      - name: Checkout sources
        uses: actions/checkout@v4
      - run: cargo check

  test:
    name: Test Suite
    runs-on: ubuntu-latest
    steps:
      - name: Checkout sources
        uses: actions/checkout@v4
      - run: cargo test --all-features --verbose --workspace

  coverage:
    name: Test Coverage
    runs-on: ubuntu-latest
    steps:
      - name: Install tarpaulin
        run: cargo install cargo-tarpaulin

      - name: Checkout sources
        uses: actions/checkout@v4

      - name: Run tarpaulin
        run: cargo tarpaulin --workspace --all-features --exclude xml_derive --coveralls ${{ secrets.COVERALLS_REPO_TOKEN }}

  lints:
    name: Lints
    runs-on: ubuntu-latest
    steps:
      - run: rustup component add rustfmt clippy

      - name: Checkout sources
        uses: actions/checkout@v4

      - name: Run cargo fmt
        run: cargo fmt --all -- --check

      - name: Run cargo clippy
        run: cargo clippy -- -D warnings
